# Generated by Django 5.2.8 on 2025-12-03 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season_year', models.IntegerField(default=2025)),
                ('scoring_mode', models.CharField(choices=[('FIXED', 'Fixed'), ('CUSTOM', 'Custom (Commissioner Editable)')], default='FIXED', max_length=10)),
                ('commissioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissioned_leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_snake', models.BooleanField(default=True)),
                ('time_per_pick_seconds', models.IntegerField(default=90)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('draft_order_generated', models.BooleanField(default=False)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhl_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_exception', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('shoots', models.CharField(blank=True, max_length=1, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('headshot', models.URLField(blank=True, null=True)),
                ('on_waivers', models.BooleanField(default=False)),
                ('waiver_expires', models.DateTimeField(blank=True, null=True)),
                ('games_played', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('plus_minus', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('fantasy_score', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.playerposition')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('allowed_player_positions', models.ManyToManyField(blank=True, related_name='allowed_in_positions', to='league.playerposition')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'unique_together': {('league', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('pick_number', models.IntegerField()),
                ('overall_number', models.IntegerField()),
                ('is_selected', models.BooleanField(default=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.draft')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.draft')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DailyLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'unique_together': {('team', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeagueRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COMMISSIONER', 'Commissioner'), ('CO_COMMISSIONER', 'Co-Commissioner'), ('MANAGER', 'Manager')], max_length=20)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('league', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.dailylineup')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.position')),
            ],
            options={
                'unique_together': {('lineup', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='ScoringCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('league', 'stat_key')},
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
    ]
