# Generated by Django 5.2.8 on 2025-11-20 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season_year', models.IntegerField(default=2025)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhl_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('C', 'Center'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('D', 'Defense'), ('G', 'Goalie'), ('IR', 'Injured Reserve')], max_length=2)),
                ('nhl_team', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RosterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centers', models.IntegerField(default=2)),
                ('wingers', models.IntegerField(default=4)),
                ('defense', models.IntegerField(default=4)),
                ('goalies', models.IntegerField(default=2)),
                ('bench', models.IntegerField(default=4)),
                ('ir', models.IntegerField(default=1)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'unique_together': {('team', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=5)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.dailylineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
            ],
            options={
                'unique_together': {('lineup', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
    ]
