# Generated by Django 5.2.8 on 2026-01-05 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhl_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=120)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('number', models.CharField(blank=True, max_length=10)),
                ('shoots', models.CharField(blank=True, max_length=10)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('fantasy_score', models.FloatField(default=0.0)),
                ('on_waivers', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season_year', models.IntegerField(default=2025)),
                ('scoring_mode', models.CharField(choices=[('FIXED', 'Fixed'), ('CUSTOM', 'Custom (Commissioner Editable)')], default='FIXED', max_length=10)),
                ('invite_code', models.CharField(blank=True, db_index=True, max_length=12, unique=True)),
                ('skater_waiver_hours', models.PositiveIntegerField(default=72)),
                ('goalie_waiver_hours', models.PositiveIntegerField(default=48)),
                ('max_roster_size', models.PositiveIntegerField(default=20)),
                ('bench_slots', models.PositiveIntegerField(default=3)),
                ('ir_slots', models.PositiveIntegerField(default=2)),
                ('lock_hour', models.PositiveSmallIntegerField(default=17)),
                ('lock_minute', models.PositiveSmallIntegerField(default=0)),
                ('commissioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissioned_leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('draft_type', models.CharField(choices=[('SNAKE', 'Snake'), ('LINEAR', 'Linear')], default='SNAKE', max_length=10)),
                ('order_mode', models.CharField(choices=[('RANDOM', 'Random'), ('MANUAL', 'Manual'), ('ALPHA', 'Alphabetical')], default='RANDOM', max_length=10)),
                ('rounds', models.PositiveIntegerField(default=16)),
                ('time_per_pick', models.PositiveIntegerField(default=120, help_text='Seconds per pick')),
                ('is_active', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_pick', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalie_waiver_hours', models.IntegerField(default=48)),
                ('skater_waiver_hours', models.IntegerField(default=72)),
                ('weekly_move_limit', models.IntegerField(default=4)),
                ('goalie_min_games', models.IntegerField(default=3)),
                ('slots_c', models.IntegerField(default=2)),
                ('slots_lw', models.IntegerField(default=2)),
                ('slots_rw', models.IntegerField(default=2)),
                ('slots_f', models.IntegerField(default=1)),
                ('slots_d', models.IntegerField(default=4)),
                ('slots_g', models.IntegerField(default=2)),
                ('slots_bn', models.IntegerField(default=3)),
                ('slots_ir', models.IntegerField(default=2)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAdvancedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2024-25', max_length=9)),
                ('corsi_for', models.FloatField(default=0)),
                ('corsi_against', models.FloatField(default=0)),
                ('corsi_pct', models.FloatField(default=0)),
                ('fenwick_for', models.FloatField(default=0)),
                ('fenwick_against', models.FloatField(default=0)),
                ('fenwick_pct', models.FloatField(default=0)),
                ('xg', models.FloatField(default=0)),
                ('ixg', models.FloatField(default=0)),
                ('xga', models.FloatField(default=0)),
                ('xgf_pct', models.FloatField(default=0)),
                ('hdcf', models.FloatField(default=0)),
                ('hdca', models.FloatField(default=0)),
                ('hdcf_pct', models.FloatField(default=0)),
                ('points_per_60', models.FloatField(default=0)),
                ('goals_per_60', models.FloatField(default=0)),
                ('assists_per_60', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('slots', models.PositiveSmallIntegerField(default=0)),
                ('allowed_player_positions', models.ManyToManyField(blank=True, related_name='allowed_in_positions', to='league.playerposition')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'unique_together': {('league', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ScoringCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('lower_is_better', models.BooleanField(default=False)),
                ('is_goalie', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('league', 'stat_key')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('league', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('processed', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matchups', to='league.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matchups', to='league.team')),
            ],
            options={
                'unique_together': {('league', 'date', 'home_team', 'away_team')},
            },
        ),
        migrations.CreateModel(
            name='DailyLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'unique_together': {('team', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('vetoed', models.BooleanField(default=False)),
                ('commissioner_note', models.CharField(blank=True, max_length=200, null=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_sent', to='league.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items_out', to='league.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_items_in', to='league.team')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='league.trade')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COMMISSIONER', 'Commissioner'), ('CO_COMMISSIONER', 'Co-Commissioner'), ('MANAGER', 'Manager')], max_length=20)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('league', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.dailylineup')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.position')),
            ],
            options={
                'unique_together': {('lineup', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='MatchupCategoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_value', models.FloatField(default=0)),
                ('away_value', models.FloatField(default=0)),
                ('winner', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away'), ('TIE', 'Tie')], default='TIE', max_length=10)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_results', to='league.matchup')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.scoringcategory')),
            ],
            options={
                'unique_together': {('matchup', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('pick_number', models.PositiveIntegerField()),
                ('made_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='league.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'ordering': ['pick_number'],
                'unique_together': {('draft', 'pick_number')},
            },
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='league.draft')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('draft', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TeamCategoryTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.scoringcategory')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'unique_together': {('team', 'date', 'category')},
            },
        ),
    ]
