# Generated by Django 5.2.8 on 2025-12-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='injury_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
