# Generated by Django 5.2.8 on 2026-01-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='current_pick_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ON_CLOCK', 'On the clock'), ('MADE', 'Made'), ('AUTO', 'Auto-picked')], default='UPCOMING', max_length=10),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='made_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player'),
        ),
    ]
