# Generated by Django 5.2.8 on 2025-11-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_league_commissioner_leaguerole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='owner',
            new_name='manager',
        ),
    ]
