# Generated by Django 5.2.8 on 2026-01-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_draft_current_pick_started_at_draftpick_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='original_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_picks_original', to='league.team'),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_picks_owned', to='league.team'),
        ),
    ]
