# Generated by Django 5.2.8 on 2025-12-09 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_player_injured_player_injury_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalie_waiver_hours', models.IntegerField(default=48)),
                ('skater_waiver_hours', models.IntegerField(default=72)),
                ('weekly_move_limit', models.IntegerField(default=4)),
                ('goalie_min_games', models.IntegerField(default=3)),
                ('slots_c', models.IntegerField(default=2)),
                ('slots_lw', models.IntegerField(default=2)),
                ('slots_rw', models.IntegerField(default=2)),
                ('slots_f', models.IntegerField(default=1)),
                ('slots_d', models.IntegerField(default=4)),
                ('slots_g', models.IntegerField(default=2)),
                ('slots_bn', models.IntegerField(default=3)),
                ('slots_ir', models.IntegerField(default=2)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAdvancedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2024-25', max_length=9)),
                ('corsi_for', models.FloatField(default=0)),
                ('corsi_against', models.FloatField(default=0)),
                ('corsi_pct', models.FloatField(default=0)),
                ('fenwick_for', models.FloatField(default=0)),
                ('fenwick_against', models.FloatField(default=0)),
                ('fenwick_pct', models.FloatField(default=0)),
                ('xg', models.FloatField(default=0)),
                ('ixg', models.FloatField(default=0)),
                ('xga', models.FloatField(default=0)),
                ('xgf_pct', models.FloatField(default=0)),
                ('hdcf', models.FloatField(default=0)),
                ('hdca', models.FloatField(default=0)),
                ('hdcf_pct', models.FloatField(default=0)),
                ('points_per_60', models.FloatField(default=0)),
                ('goals_per_60', models.FloatField(default=0)),
                ('assists_per_60', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
            ],
        ),
    ]
