# Generated by Django 5.2.8 on 2026-01-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_draftpick_original_team_alter_draftpick_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nhl_team_abbr',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3),
        ),
    ]
