# Generated by Django 5.2.8 on 2026-01-07 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_player_nhl_team_abbr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailylineup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyslot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='draftorder',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='draftpick',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leaguerole',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='scoringcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailylineup',
            constraint=models.UniqueConstraint(fields=('team', 'date'), name='uniq_daily_lineup_team_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyslot',
            constraint=models.UniqueConstraint(fields=('lineup', 'slot'), name='uniq_daily_slot_lineup_slot'),
        ),
        migrations.AddConstraint(
            model_name='draftorder',
            constraint=models.UniqueConstraint(fields=('draft', 'position'), name='uniq_draft_order_position'),
        ),
        migrations.AddConstraint(
            model_name='draftorder',
            constraint=models.UniqueConstraint(fields=('draft', 'team'), name='uniq_draft_order_team'),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'pick_number'), name='uniq_draft_pick_number'),
        ),
        migrations.AddConstraint(
            model_name='leaguerole',
            constraint=models.UniqueConstraint(fields=('league', 'user'), name='uniq_league_role'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('league', 'code'), name='uniq_position_code_per_league'),
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('team', 'player'), name='uniq_roster_team_player'),
        ),
        migrations.AddConstraint(
            model_name='scoringcategory',
            constraint=models.UniqueConstraint(fields=('league', 'stat_key'), name='uniq_scoring_key_per_league'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('league', 'name'), name='uniq_team_name_per_league'),
        ),
    ]
