# Generated by Django 5.2.8 on 2025-12-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_trade_tradeitem_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='bench_slots',
            field=models.PositiveIntegerField(default=3, help_text='Number of bench slots per team.'),
        ),
        migrations.AddField(
            model_name='league',
            name='goalie_waiver_hours',
            field=models.PositiveIntegerField(default=48, help_text='Waiver duration in hours for goalies.'),
        ),
        migrations.AddField(
            model_name='league',
            name='ir_slots',
            field=models.PositiveIntegerField(default=2, help_text='Number of IR slots per team.'),
        ),
        migrations.AddField(
            model_name='league',
            name='lock_hour',
            field=models.PositiveSmallIntegerField(default=17, help_text='Hour of day (0–23) when daily lineups lock.'),
        ),
        migrations.AddField(
            model_name='league',
            name='lock_minute',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minute of hour (0–59) when daily lineups lock.'),
        ),
        migrations.AddField(
            model_name='league',
            name='max_roster_size',
            field=models.PositiveIntegerField(default=20, help_text='Total max players on a team (including bench and IR).'),
        ),
        migrations.AddField(
            model_name='league',
            name='skater_waiver_hours',
            field=models.PositiveIntegerField(default=72, help_text='Waiver duration in hours for skaters.'),
        ),
        migrations.AddField(
            model_name='tradeitem',
            name='to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_items_in', to='league.team'),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='from_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items_out', to='league.team'),
        ),
    ]
