# Generated by Django 5.2.8 on 2025-11-26 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_team_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('plus_minus', models.IntegerField(default=0)),
                ('pim', models.IntegerField(default=0)),
                ('ppp', models.IntegerField(default=0)),
                ('shg', models.IntegerField(default=0)),
                ('gwg', models.IntegerField(default=0)),
                ('sog', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('shutouts', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
            ],
        ),
    ]
