# Generated by Django 5.2.8 on 2025-11-29 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_playerstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nhl_team',
        ),
        migrations.RemoveField(
            model_name='rostersettings',
            name='wingers',
        ),
        migrations.AddField(
            model_name='league',
            name='scoring_mode',
            field=models.CharField(choices=[('FIXED', 'Fixed (Standard Yahoo-style)'), ('CUSTOM', 'Custom (Commissioner editable)')], default='FIXED', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fantasy_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='headshot',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='on_waivers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='plus_minus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='shoots',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='waiver_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rostersettings',
            name='left_wing',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rostersettings',
            name='right_wing',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='rostersettings',
            name='goalies',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rostersettings',
            name='ir',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='LeagueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_priority', models.CharField(default='C,LW,RW,D,G', max_length=50)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'unique_together': {('league', 'stat_key')},
            },
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
