# Generated by Django 5.2.8 on 2025-12-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_league_bench_slots_league_goalie_waiver_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='slots',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('processed', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matchups', to='league.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matchups', to='league.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'unique_together': {('league', 'date', 'home_team', 'away_team')},
            },
        ),
        migrations.CreateModel(
            name='MatchupCategoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_value', models.FloatField(default=0)),
                ('away_value', models.FloatField(default=0)),
                ('winner', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away'), ('TIE', 'Tie')], default='TIE', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.scoringcategory')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_results', to='league.matchup')),
            ],
            options={
                'unique_together': {('matchup', 'category')},
            },
        ),
        migrations.CreateModel(
            name='TeamCategoryTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.scoringcategory')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'unique_together': {('team', 'date', 'category')},
            },
        ),
    ]
