# Generated by Django 5.2.8 on 2026-01-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_dailylineup_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftpick',
            options={'ordering': ['round_number', 'pick_number']},
        ),
        migrations.RemoveConstraint(
            model_name='draftpick',
            name='uniq_draft_pick_number',
        ),
        migrations.AddField(
            model_name='player',
            name='adp',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'round_number', 'pick_number'), name='uniq_draft_round_pick_number'),
        ),
    ]
