# Generated by Django 5.2.8 on 2025-12-01 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_remove_player_name_remove_player_nhl_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='rostersettings',
            name='league',
        ),
        migrations.AlterField(
            model_name='dailyslot',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='scoring_mode',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('CUSTOM', 'Custom (Commissioner Editable)')], default='FIXED', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaguerole',
            name='role',
            field=models.CharField(choices=[('COMMISSIONER', 'Commissioner'), ('CO_COMMISSIONER', 'Co-Commissioner'), ('MANAGER', 'Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.playerposition'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_lineup_slot', models.BooleanField(default=True)),
                ('allowed_player_positions', models.ManyToManyField(blank=True, related_name='valid_lineup_slots', to='league.playerposition')),
            ],
        ),
        migrations.AlterField(
            model_name='dailyslot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.position'),
        ),
        migrations.DeleteModel(
            name='LeagueSettings',
        ),
        migrations.DeleteModel(
            name='RosterSettings',
        ),
    ]
