# Generated by Django 5.2.8 on 2025-12-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_position_slots_matchup_matchupcategoryresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='scoringcategory',
            name='is_goalie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoringcategory',
            name='lower_is_better',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='league',
            name='bench_slots',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='league',
            name='goalie_waiver_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AlterField(
            model_name='league',
            name='ir_slots',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='league',
            name='lock_hour',
            field=models.PositiveSmallIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='league',
            name='lock_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='max_roster_size',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='league',
            name='skater_waiver_hours',
            field=models.PositiveIntegerField(default=72),
        ),
    ]
