# Generated by Django 5.2.8 on 2026-01-02 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_league_invite_code_scoringcategory_is_goalie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftpick',
            options={'ordering': ['pick_number']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='draft',
            name='draft_order_generated',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='is_snake',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='time_per_pick_seconds',
        ),
        migrations.AlterUniqueTogether(
            name='draftpick',
            unique_together={('draft', 'pick_number')},
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='headshot',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='player',
            name='injured',
        ),
        migrations.RemoveField(
            model_name='player',
            name='injury_note',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_exception',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='plus_minus',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shots',
        ),
        migrations.RemoveField(
            model_name='player',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='player',
            name='waiver_expires',
        ),
        migrations.AddField(
            model_name='draft',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='current_pick',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='draft',
            name='draft_type',
            field=models.CharField(choices=[('SNAKE', 'Snake'), ('LINEAR', 'Linear')], default='SNAKE', max_length=10),
        ),
        migrations.AddField(
            model_name='draft',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draft',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draft',
            name='order_mode',
            field=models.CharField(choices=[('RANDOM', 'Random'), ('MANUAL', 'Manual'), ('ALPHA', 'Alphabetical')], default='RANDOM', max_length=10),
        ),
        migrations.AddField(
            model_name='draft',
            name='rounds',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='draft',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='Commissioner scheduled draft start time', null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='time_per_pick',
            field=models.PositiveIntegerField(default=120, help_text='Seconds per pick'),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='made_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='league',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='league.league'),
        ),
        migrations.AlterField(
            model_name='draftorder',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='league.draft'),
        ),
        migrations.AlterField(
            model_name='draftorder',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='league.draft'),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='pick_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player'),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='round_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='full_name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='player',
            name='games_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='nhl_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='shoots',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='draftorder',
            unique_together={('draft', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('league', 'name')},
        ),
        migrations.RemoveField(
            model_name='draftpick',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='draftpick',
            name='overall_number',
        ),
    ]
